import { Roboto } from 'next/font/google'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
});

import type { Metadata } from "next";
import "./globals.css";
import AppHeader from '../../components/AppHeader';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className}`}>
        <div className='app-container'>
          <AppHeader />
          <div className='app-child'>{children}</div>
          
        </div>
      </body>
    </html>
  );
}
